// <auto-generated />
using System;
using CookManagement.VSA.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CookManagement.VSA.Infrastructure.Data.Migrations
{
    [DbContext(typeof(CookDbContext))]
    [Migration("20251125004744_AddProductNameToUserRecords")]
    partial class AddProductNameToUserRecords
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CookManagement.VSA.Shared.Entities.BarInventory", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("CurrentStock")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int>("MinimumStock")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("Product")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Code");

                    b.ToTable("BarInventory");
                });

            modelBuilder.Entity("CookManagement.VSA.Shared.Entities.KitchenInventory", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("CurrentStock")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("MeasurementUnit")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("MinimumStock")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("Product")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Code");

                    b.ToTable("KitchenInventory");
                });

            modelBuilder.Entity("CookManagement.VSA.Shared.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Víctor Castro",
                            Password = "$2a$11$6ssgrCTy2PpEFMHwJIy8IultnEW1G3e9Js9mA1JTzKbLmNFCGV5o2",
                            Role = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Gabriel Castillo",
                            Password = "$2a$11$eB7Dw.gQjmDhvh1apI.LJuzMvaPeDXryxLgsPMW//TGzkEb0fj85i",
                            Role = "Admin"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Perla Casco",
                            Password = "$2a$11$GKxRzL6yrT/cFGHBN8xcbud9E53L2.PrfdgqIscpSASMH1HqO6M.K",
                            Role = "Admin"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Sherlyn Murillo",
                            Password = "$2a$11$EtKTjfk5UU1HrRup3ntVrevtEp.uIcNZ0BpiNblMcXCEpuUhEniy2",
                            Role = "Bar"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Ilsi Padilla",
                            Password = "$2a$11$NL2/i1p9mO2iJSGhLsi78.m1rAQ0t7BjPa3I5D6D6CkOyh9mLYiSe",
                            Role = "Bar"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Alexis Valdez",
                            Password = "$2a$11$iaVotQmmcaJ9eIxSizJnBuEZnmPa8h2WbAj7C5pdu6uu9qNYIjaSu",
                            Role = "Cocina"
                        },
                        new
                        {
                            Id = 5,
                            Name = "María Fonseca",
                            Password = "$2a$11$obJ80dKMf4FCL1Wa4M2z1eNHUV/ctwCsWk0pKUC73k79X9hn7ohqe",
                            Role = "Cocina"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Astrid Valle",
                            Password = "$2a$11$87M/S6.qvQTUcyPLQM6UjO3qhtpRu9E3T43eJs3QHPqR5bzw83Dg.",
                            Role = "Cocina"
                        });
                });

            modelBuilder.Entity("CookManagement.VSA.Shared.Entities.UserRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Courtesy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValue(new DateTimeOffset(new DateTime(2025, 11, 24, 18, 47, 42, 767, DateTimeKind.Unspecified).AddTicks(7734), new TimeSpan(0, -6, 0, 0, 0)));

                    b.Property<int>("Damaged")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int>("Entries")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int>("FinalInventory")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int>("InitialInventory")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("InventoryType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProductCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Sales")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValue(new DateTimeOffset(new DateTime(2025, 11, 24, 18, 47, 42, 767, DateTimeKind.Unspecified).AddTicks(8503), new TimeSpan(0, -6, 0, 0, 0)));

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "ProductCode", "CreatedAt")
                        .HasDatabaseName("IX_UserRecords_UserId_ProductCode_CreatedAt");

                    b.ToTable("UserRecords");
                });

            modelBuilder.Entity("CookManagement.VSA.Shared.Entities.UserRecord", b =>
                {
                    b.HasOne("CookManagement.VSA.Shared.Entities.User", "User")
                        .WithMany("UserRecords")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CookManagement.VSA.Shared.Entities.User", b =>
                {
                    b.Navigation("UserRecords");
                });
#pragma warning restore 612, 618
        }
    }
}
