// <auto-generated />
using System;
using CookManagement.VSA.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CookManagement.VSA.Infrastructure.Data.Migrations
{
    [DbContext(typeof(CookDbContext))]
    [Migration("20260113044559_AddNewUsers")]
    partial class AddNewUsers
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CookManagement.VSA.Shared.Entities.BarInventory", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<double>("CurrentStock")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("double precision")
                        .HasDefaultValue(0.0);

                    b.Property<double>("MinimumStock")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("double precision")
                        .HasDefaultValue(0.0);

                    b.Property<string>("Product")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Code");

                    b.ToTable("BarInventory");
                });

            modelBuilder.Entity("CookManagement.VSA.Shared.Entities.KitchenInventory", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<double>("CurrentStock")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("double precision")
                        .HasDefaultValue(0.0);

                    b.Property<string>("MeasurementUnit")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<double>("MinimumStock")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("double precision")
                        .HasDefaultValue(0.0);

                    b.Property<string>("Product")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Code");

                    b.ToTable("KitchenInventory");
                });

            modelBuilder.Entity("CookManagement.VSA.Shared.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Vcastro",
                            Password = "$2a$11$REAfSznGeEc/Znk77Htx7OX33HEulgxqicDF4Szd2yVUAC0HmQeZC",
                            Role = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Gcastillo",
                            Password = "$2a$11$Fuh8LvVLwEw3ertU3ZS0pO0Hl1vEQr7fM5OWCT4JhdQOgMeuWMnnS",
                            Role = "Admin"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Pcasco",
                            Password = "$2a$11$w7UpmeGBC8B2V7eWXYH93e7ptsEZibk8rvnoBXwXE6FP9UR/KxPNa",
                            Role = "Admin"
                        },
                        new
                        {
                            Id = 7,
                            Name = "SherMurillo",
                            Password = "$2a$11$nk/GVbJLCjUsNuQlv7cK5u9enEN.HhfFuEbxXC2sexeu0RzagMPqG",
                            Role = "Bar"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Elinuñez",
                            Password = "$2a$11$rcVIjn1iZ/aWIDJjJ35truMlSFN/6waR5F6.G9f3H0ck7usmwecZa",
                            Role = "Bar"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Lorebustillo",
                            Password = "$2a$11$loKK6dbPBuWGmai4HOfx6.nUMOLqIzD5XpnTy0VQEPBNE1OHoPaSm",
                            Role = "Bar"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Elisanchez",
                            Password = "$2a$11$woU1KtL6iAv07y894MMpOuEqSnf4TRk6m.pX/xljv8cZgc2/5xkXS",
                            Role = "Bar"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Alevaldez",
                            Password = "$2a$11$OvurlxftIiFNcq4c3kDNnu6qJ5QQ4YCv149qcemIj65MSJzIuicZy",
                            Role = "Cocina"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Marifonseca",
                            Password = "$2a$11$4cINv0.do.dmaZYgHw27AOdAmvlluglpL.aK.s9HpOXvriZ1tGyti",
                            Role = "Cocina"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Astridvalle",
                            Password = "$2a$11$aYFBaZkJFjJG3kJO2VBpzezRzQkRn.IK2M2bSxNTokpi2hA6YXe/u",
                            Role = "Cocina"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Jcastillo",
                            Password = "$2a$11$G3uQiwH.j9UdyiQGoHeghOttoYu0xW9W2SeBhQ8wtX9q4he4.MkcG",
                            Role = "Cocina"
                        },
                        new
                        {
                            Id = 12,
                            Name = "AdminLinus",
                            Password = "$2a$11$S/80J1F/Tsfau6nkXBPaYufOqU59dnnnc2M12IHTPT17uKjevkyEi",
                            Role = "SuperAdmin"
                        });
                });

            modelBuilder.Entity("CookManagement.VSA.Shared.Entities.UserRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("Courtesy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("double precision")
                        .HasDefaultValue(0.0);

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValue(new DateTimeOffset(new DateTime(2026, 1, 12, 22, 45, 56, 533, DateTimeKind.Unspecified).AddTicks(8337), new TimeSpan(0, -6, 0, 0, 0)));

                    b.Property<double>("DailyMove")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("double precision")
                        .HasDefaultValue(0.0);

                    b.Property<double>("Damaged")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("double precision")
                        .HasDefaultValue(0.0);

                    b.Property<double>("Difference")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("double precision")
                        .HasDefaultValue(0.0);

                    b.Property<int>("Entries")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<double>("FinalInventory")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("double precision")
                        .HasDefaultValue(0.0);

                    b.Property<double>("InitialInventory")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("double precision")
                        .HasDefaultValue(0.0);

                    b.Property<string>("InventoryType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProductCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<double>("Remains")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("double precision")
                        .HasDefaultValue(0.0);

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValue(new DateTimeOffset(new DateTime(2026, 1, 12, 22, 45, 56, 533, DateTimeKind.Unspecified).AddTicks(9163), new TimeSpan(0, -6, 0, 0, 0)));

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "ProductCode", "CreatedAt")
                        .HasDatabaseName("IX_UserRecords_UserId_ProductCode_CreatedAt");

                    b.ToTable("UserRecords");
                });

            modelBuilder.Entity("CookManagement.VSA.Shared.Entities.UserRecord", b =>
                {
                    b.HasOne("CookManagement.VSA.Shared.Entities.User", "User")
                        .WithMany("UserRecords")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CookManagement.VSA.Shared.Entities.User", b =>
                {
                    b.Navigation("UserRecords");
                });
#pragma warning restore 612, 618
        }
    }
}
