// <auto-generated />
using System;
using CookManagement.VSA.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CookManagement.VSA.Infrastructure.Data.Migrations
{
    [DbContext(typeof(CookDbContext))]
    [Migration("20260107214916_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CookManagement.VSA.Shared.Entities.BarInventory", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<double>("CurrentStock")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("double precision")
                        .HasDefaultValue(0.0);

                    b.Property<double>("MinimumStock")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("double precision")
                        .HasDefaultValue(0.0);

                    b.Property<string>("Product")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Code");

                    b.ToTable("BarInventory");
                });

            modelBuilder.Entity("CookManagement.VSA.Shared.Entities.KitchenInventory", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<double>("CurrentStock")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("double precision")
                        .HasDefaultValue(0.0);

                    b.Property<string>("MeasurementUnit")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<double>("MinimumStock")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("double precision")
                        .HasDefaultValue(0.0);

                    b.Property<string>("Product")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Code");

                    b.ToTable("KitchenInventory");
                });

            modelBuilder.Entity("CookManagement.VSA.Shared.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Vcastro",
                            Password = "$2a$11$aElS0hr6kgwIr0X.brMh5uuTvi73CQW5GABfYPFKusabGwUWdyO16",
                            Role = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Gcastillo",
                            Password = "$2a$11$blGVpdghJa.CegLgvKG8qO9qUgqOaEHSJHizAWRiYQrAX9mziUMn2",
                            Role = "Admin"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Pcasco",
                            Password = "$2a$11$CjVUWTGXwxY4vNKRd0lYAexfYotn/r8yFde.CyP55bhkKgdYKXqUa",
                            Role = "Admin"
                        },
                        new
                        {
                            Id = 7,
                            Name = "SherMurillo",
                            Password = "$2a$11$cc9VqcLdY8uKe8HXF/IXEuPahlEkZc6b6E6.zeM7CX1tgeo50Reo6",
                            Role = "Bar"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Elinuñez",
                            Password = "$2a$11$DYn0HSFfeH3waYcTURasIOr2moezNVVfvWGv7vsq7STKwPce1P.ju",
                            Role = "Bar"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Gperez",
                            Password = "$2a$11$mGbF86VoAmOWm0SednWlm.bbGnCmfigGOBpZVcHTT2O5nmmttujei",
                            Role = "Bar"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Alevaldez",
                            Password = "$2a$11$WClTW5H6sFdmCCwpora9auu42eaf0A7I8XnvOZCp0GhFNOamqatfe",
                            Role = "Cocina"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Marifonseca",
                            Password = "$2a$11$sKvEiP3IeT6loYwNUNcH6uejIOvFJgX47eGzspu7zvoOavBhClpDu",
                            Role = "Cocina"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Astridvalle",
                            Password = "$2a$11$seXD2yWRfoHwwpOuoerdWOeq.JJVlMbE.PPtAXZQWgwYIAeOOJM1i",
                            Role = "Cocina"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Jcastillo",
                            Password = "$2a$11$fiwD6A0qlX4pzdC339j8auS794DMzFBpnfu0WuRlcxLlJReZSWlrO",
                            Role = "Cocina"
                        },
                        new
                        {
                            Id = 11,
                            Name = "AdminLinus",
                            Password = "$2a$11$VXyDpEc.0Ib96s8LpT.51OKfNYAE6HnswSnvW0ZsMMRHr1NdC6wf.",
                            Role = "SuperAdmin"
                        });
                });

            modelBuilder.Entity("CookManagement.VSA.Shared.Entities.UserRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Courtesy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValue(new DateTimeOffset(new DateTime(2026, 1, 7, 15, 49, 12, 456, DateTimeKind.Unspecified).AddTicks(1854), new TimeSpan(0, -6, 0, 0, 0)));

                    b.Property<int>("DailyMove")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int>("Damaged")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int>("Difference")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int>("Entries")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int>("FinalInventory")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int>("InitialInventory")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("InventoryType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProductCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Remains")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValue(new DateTimeOffset(new DateTime(2026, 1, 7, 15, 49, 12, 456, DateTimeKind.Unspecified).AddTicks(3366), new TimeSpan(0, -6, 0, 0, 0)));

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "ProductCode", "CreatedAt")
                        .HasDatabaseName("IX_UserRecords_UserId_ProductCode_CreatedAt");

                    b.ToTable("UserRecords");
                });

            modelBuilder.Entity("CookManagement.VSA.Shared.Entities.UserRecord", b =>
                {
                    b.HasOne("CookManagement.VSA.Shared.Entities.User", "User")
                        .WithMany("UserRecords")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CookManagement.VSA.Shared.Entities.User", b =>
                {
                    b.Navigation("UserRecords");
                });
#pragma warning restore 612, 618
        }
    }
}
