// <auto-generated />
using System;
using CookManagement.VSA.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CookManagement.VSA.Infrastructure.Data.Migrations
{
    [DbContext(typeof(CookDbContext))]
    [Migration("20260111041112_ChangeIntToDouble")]
    partial class ChangeIntToDouble
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CookManagement.VSA.Shared.Entities.BarInventory", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<double>("CurrentStock")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("double precision")
                        .HasDefaultValue(0.0);

                    b.Property<double>("MinimumStock")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("double precision")
                        .HasDefaultValue(0.0);

                    b.Property<string>("Product")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Code");

                    b.ToTable("BarInventory");
                });

            modelBuilder.Entity("CookManagement.VSA.Shared.Entities.KitchenInventory", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<double>("CurrentStock")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("double precision")
                        .HasDefaultValue(0.0);

                    b.Property<string>("MeasurementUnit")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<double>("MinimumStock")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("double precision")
                        .HasDefaultValue(0.0);

                    b.Property<string>("Product")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Code");

                    b.ToTable("KitchenInventory");
                });

            modelBuilder.Entity("CookManagement.VSA.Shared.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Vcastro",
                            Password = "$2a$11$cB2aRwke1qM.tKH.BmQhBuo9SY.4xFgOU1e0M8qG8cOK7TevW9BxS",
                            Role = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Gcastillo",
                            Password = "$2a$11$pZ5knWvB2drorA.x0iSH/.R/eMUyQzA9xCM4lvTUyxbsZms.JDM5C",
                            Role = "Admin"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Pcasco",
                            Password = "$2a$11$D2jELz.WRh80Rlpf1rhqzO0PJGQQSC6WY397TsN2rRRwf7lotNSMS",
                            Role = "Admin"
                        },
                        new
                        {
                            Id = 7,
                            Name = "SherMurillo",
                            Password = "$2a$11$KDv35iuu.esflAYmYD6dh.WeFFAwf6yW1GKsR1AcGyKxhPrb5VRdi",
                            Role = "Bar"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Elinuñez",
                            Password = "$2a$11$xsQe8Jbu2KiH.WjLuTv29etltFOo8pEIRtRsCdyn2lPxaqyqPD1aq",
                            Role = "Bar"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Gperez",
                            Password = "$2a$11$7iVypxRYKrDBjjdxWGobYuXRT5mt1Ah7NM2ydth4j0BOTWe9gB0DW",
                            Role = "Bar"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Alevaldez",
                            Password = "$2a$11$MRhizFdZeAvEw6WCcIJpruHDWw1dBTSexwQRxGt8dNIxFNlmT9dj6",
                            Role = "Cocina"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Marifonseca",
                            Password = "$2a$11$WaobqhXU46V5Tni2sqFE5u.rZH570fe282kYOmji2BAJvLgFlHewK",
                            Role = "Cocina"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Astridvalle",
                            Password = "$2a$11$Et4Xni0J98xk78IoeQTH3uZXWhMnn4VMyuBNsonhqW7myaVV/ICSy",
                            Role = "Cocina"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Jcastillo",
                            Password = "$2a$11$CkP6j0E3ai.tz50bpggYLOsTtVg4Zt4LMPM.Qw6ni.iT91Ykzwzsu",
                            Role = "Cocina"
                        },
                        new
                        {
                            Id = 11,
                            Name = "AdminLinus",
                            Password = "$2a$11$5OI5E71AEc0msfe6/DWwx.rfh9bzvGqqKzKQtwPiAgHi2n1tQ36tG",
                            Role = "SuperAdmin"
                        });
                });

            modelBuilder.Entity("CookManagement.VSA.Shared.Entities.UserRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("Courtesy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("double precision")
                        .HasDefaultValue(0.0);

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValue(new DateTimeOffset(new DateTime(2026, 1, 10, 22, 11, 9, 274, DateTimeKind.Unspecified).AddTicks(3330), new TimeSpan(0, -6, 0, 0, 0)));

                    b.Property<double>("DailyMove")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("double precision")
                        .HasDefaultValue(0.0);

                    b.Property<double>("Damaged")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("double precision")
                        .HasDefaultValue(0.0);

                    b.Property<double>("Difference")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("double precision")
                        .HasDefaultValue(0.0);

                    b.Property<int>("Entries")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<double>("FinalInventory")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("double precision")
                        .HasDefaultValue(0.0);

                    b.Property<double>("InitialInventory")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("double precision")
                        .HasDefaultValue(0.0);

                    b.Property<string>("InventoryType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProductCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<double>("Remains")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("double precision")
                        .HasDefaultValue(0.0);

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValue(new DateTimeOffset(new DateTime(2026, 1, 10, 22, 11, 9, 274, DateTimeKind.Unspecified).AddTicks(4001), new TimeSpan(0, -6, 0, 0, 0)));

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "ProductCode", "CreatedAt")
                        .HasDatabaseName("IX_UserRecords_UserId_ProductCode_CreatedAt");

                    b.ToTable("UserRecords");
                });

            modelBuilder.Entity("CookManagement.VSA.Shared.Entities.UserRecord", b =>
                {
                    b.HasOne("CookManagement.VSA.Shared.Entities.User", "User")
                        .WithMany("UserRecords")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CookManagement.VSA.Shared.Entities.User", b =>
                {
                    b.Navigation("UserRecords");
                });
#pragma warning restore 612, 618
        }
    }
}
