// <auto-generated />
using System;
using CookManagement.VSA.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CookManagement.VSA.Infrastructure.Data.Migrations
{
    [DbContext(typeof(CookDbContext))]
    [Migration("20260106052020_ChangedStockNumberType")]
    partial class ChangedStockNumberType
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CookManagement.VSA.Shared.Entities.BarInventory", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<double>("CurrentStock")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("double precision")
                        .HasDefaultValue(0.0);

                    b.Property<double>("MinimumStock")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("double precision")
                        .HasDefaultValue(0.0);

                    b.Property<string>("Product")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Code");

                    b.ToTable("BarInventory");
                });

            modelBuilder.Entity("CookManagement.VSA.Shared.Entities.KitchenInventory", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<double>("CurrentStock")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("double precision")
                        .HasDefaultValue(0.0);

                    b.Property<string>("MeasurementUnit")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<double>("MinimumStock")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("double precision")
                        .HasDefaultValue(0.0);

                    b.Property<string>("Product")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Code");

                    b.ToTable("KitchenInventory");
                });

            modelBuilder.Entity("CookManagement.VSA.Shared.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Vcastro",
                            Password = "$2a$11$UEkM3opzq17e8AhGeGIUYe..KGetx6gKOcqrcaFl8vc0WmrMd4Nqa",
                            Role = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Gcastillo",
                            Password = "$2a$11$r3WNHTuc0SkY02S48LrK8.Zs0Z0NQ90MDbXxPy6Xv4RTMj3TVcs86",
                            Role = "Admin"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Pcasco",
                            Password = "$2a$11$NxDwlOtpsljFJeyODG/G9eDBm8NxFKrT6/Uud.AFLSecTWgz.73um",
                            Role = "Admin"
                        },
                        new
                        {
                            Id = 7,
                            Name = "SherMurillo",
                            Password = "$2a$11$Pjr/oI5YAGz3.e7fZEx8KuqLinbYvnhmmUS36D/pCLGtTiyPf20cO",
                            Role = "Bar"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Elinuñez",
                            Password = "$2a$11$ri2dKmLr3SGlW5o2xbHC.OsAyGIC1v2niASUHVXquZFR95mazYGNm",
                            Role = "Bar"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Gperez",
                            Password = "$2a$11$C6kpQ45UpxOzIt3bBVCKhOG6mFTxn.XlYtJyg3hHyf8nEr2cAOlsW",
                            Role = "Bar"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Alevaldez",
                            Password = "$2a$11$8MNvFMZusRAWEHTu771bE.YwZfcsUUU.K2KhGMHpFHR5pzGd9l5hW",
                            Role = "Cocina"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Marifonseca",
                            Password = "$2a$11$3XqAMQKih2G84B/pW2hM9ex2bB5/AiQxt.F/0hrngUlnf7R5TQmb6",
                            Role = "Cocina"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Astridvalle",
                            Password = "$2a$11$uo9BQ6gw.QVUyZSyq6vIyO/ZLGZ1fj5e7HH2oYW7inTHLD/dliSvu",
                            Role = "Cocina"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Jcastillo",
                            Password = "$2a$11$nhyctQDc2WkVHsCr.57bvO5fH3f0slzqmlxr7MH2U6ydz/7L94poq",
                            Role = "Cocina"
                        });
                });

            modelBuilder.Entity("CookManagement.VSA.Shared.Entities.UserRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Courtesy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValue(new DateTimeOffset(new DateTime(2026, 1, 5, 23, 20, 15, 856, DateTimeKind.Unspecified).AddTicks(6818), new TimeSpan(0, -6, 0, 0, 0)));

                    b.Property<int>("DailyMove")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int>("Damaged")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int>("Difference")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int>("Entries")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int>("FinalInventory")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int>("InitialInventory")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("InventoryType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProductCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Remains")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValue(new DateTimeOffset(new DateTime(2026, 1, 5, 23, 20, 15, 856, DateTimeKind.Unspecified).AddTicks(9275), new TimeSpan(0, -6, 0, 0, 0)));

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "ProductCode", "CreatedAt")
                        .HasDatabaseName("IX_UserRecords_UserId_ProductCode_CreatedAt");

                    b.ToTable("UserRecords");
                });

            modelBuilder.Entity("CookManagement.VSA.Shared.Entities.UserRecord", b =>
                {
                    b.HasOne("CookManagement.VSA.Shared.Entities.User", "User")
                        .WithMany("UserRecords")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CookManagement.VSA.Shared.Entities.User", b =>
                {
                    b.Navigation("UserRecords");
                });
#pragma warning restore 612, 618
        }
    }
}
